name: Laravel Test Suite

on:
  push:
    branches: [ staging, dev ]
  pull_request:
    branches: [ staging, dev ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.3' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, sqlite, pdo_sqlite, bcmath, xml, ctype, json, openssl, curl, gd
          coverage: none
          ini-values: post_max_size=256M, memory_limit=512M

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env.testing
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Configure SQLite for testing
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env

      - name: Clear caches
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear

      - name: Run database migrations
        run: php artisan migrate --env=testing --force

      - name: Create test output directory
        run: mkdir -p tests/_output

      - name: Run tests
        run: |
          php artisan test --env=testing --log-junit=tests/_output/junit.xml
        continue-on-error: false

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/_output/junit.xml
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Laravel logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: laravel-logs
          path: storage/logs
          retention-days: 7
